import type { SkillsConfig } from './skills.model';

export const SKILLS_CONFIG: SkillsConfig = {
  pageTitle: 'Technical Skills',
  pageDescription:
    'Technologies and tools I work with to build modern applications',
  categories: [
    {
      title: 'Frontend Development',
      icon: 'bi-display',
      description: 'Modern web interfaces and user experiences',
      skills: [
        {
          name: 'Angular',
          icon: 'devicon-angularjs-plain',
          level: 'Expert',
          stars: 5,
          category: 'Frontend',
        },
        {
          name: 'React',
          icon: 'devicon-react-original',
          level: 'Intermediate',
          stars: 3,
          category: 'Frontend',
        },
        {
          name: 'TypeScript',
          icon: 'devicon-typescript-plain',
          level: 'Expert',
          stars: 5,
          category: 'Frontend',
        },
        {
          name: 'JavaScript',
          icon: 'devicon-javascript-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'Frontend',
        },
        {
          name: 'HTML5',
          icon: 'devicon-html5-plain',
          level: 'Expert',
          stars: 5,
          category: 'Frontend',
        },
        {
          name: 'CSS3',
          icon: 'devicon-css3-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'Frontend',
        },
        {
          name: 'SCSS',
          icon: 'devicon-sass-original',
          level: 'Advanced',
          stars: 4,
          category: 'Frontend',
        },
        {
          name: 'Bootstrap',
          icon: 'devicon-bootstrap-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'Frontend',
        },
        {
          name: 'Tailwind CSS',
          icon: 'devicon-tailwindcss-plain',
          level: 'Beginner',
          stars: 2,
          category: 'Frontend',
        },
        {
          name: 'RxJS',
          icon: 'devicon-rxjs-plain',
          level: 'Advanced',
          stars: 4,
          category: 'Frontend',
        },
      ],
    },
    {
      title: 'Backend Development',
      icon: 'bi-server',
      description: 'Server-side technologies and APIs',
      skills: [
        {
          name: 'Node.js',
          icon: 'devicon-nodejs-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Backend',
        },
        {
          name: 'Express',
          icon: 'devicon-express-original',
          level: 'Intermediate',
          stars: 3,
          category: 'Backend',
        },
        {
          name: 'NestJS',
          icon: 'devicon-nestjs-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Backend',
        },
        {
          name: 'Python',
          icon: 'devicon-python-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Backend',
        },
        {
          name: 'FastAPI',
          icon: 'devicon-fastapi-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Backend',
        },
      ],
    },
    {
      title: 'Database & Storage',
      icon: 'bi-database',
      description: 'Data management and persistence',
      skills: [
        {
          name: 'MongoDB',
          icon: 'devicon-mongodb-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Database',
        },
        {
          name: 'PostgreSQL',
          icon: 'devicon-postgresql-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Database',
        },
        {
          name: 'SQLite',
          icon: 'devicon-sqlite-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Database',
        },
        {
          name: 'typeORM',
          icon: 'devicon-typescript-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Database',
        },
        {
          name: 'sqlalchemy',
          icon: 'devicon-sqlalchemy-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Database',
        },
      ],
    },
    {
      title: 'Mobile Development',
      icon: 'bi-phone',
      description: 'Cross-platform mobile applications',
      skills: [
        {
          name: 'Ionic',
          icon: 'devicon-ionic-original',
          level: 'Advanced',
          stars: 4,
          category: 'Mobile',
        },
        {
          name: 'NativeScript',
          icon: 'devicon-typescript-plain',
          level: 'Intermediate',
          stars: 3.5,
          category: 'Mobile',
        },
      ],
    },
    {
      title: 'DevOps & Tools',
      icon: 'bi-gear',
      description: 'Development tools and deployment',
      skills: [
        {
          name: 'Git',
          icon: 'devicon-git-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'DevOps',
        },
        {
          name: 'GitHub',
          icon: 'devicon-github-original',
          level: 'Expert',
          stars: 4.5,
          category: 'DevOps',
        },
        {
          name: 'Docker',
          icon: 'devicon-docker-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'DevOps',
        },

        {
          name: 'Postman',
          icon: 'devicon-postman-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'DevOps',
        },
        {
          name: 'npm',
          icon: 'devicon-npm-original-wordmark',
          level: 'Expert',
          stars: 4.5,
          category: 'DevOps',
        },

        {
          name: 'GraphQL',
          icon: 'devicon-graphql-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'DevOps',
        },
        {
          name: 'VS Code',
          icon: 'devicon-vscode-plain',
          level: 'Expert',
          stars: 5,
          category: 'DevOps',
        },
        {
          name: 'Linux',
          icon: 'devicon-linux-plain',
          level: 'Advanced',
          stars: 4,
          category: 'DevOps',
        },
        {
          name: 'Bash',
          icon: 'devicon-bash-plain',
          level: 'Advanced',
          stars: 4,
          category: 'DevOps',
        },
        {
          name: 'Nginx',
          icon: 'devicon-nginx-original',
          level: 'Intermediate',
          stars: 3,
          category: 'DevOps',
        },
        {
          name: 'Yarn',
          icon: 'devicon-yarn-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'DevOps',
        },
        {
          name: 'Figma',
          icon: 'devicon-figma-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'DevOps',
        },
      ],
    },
    {
      title: 'Testing & Quality',
      icon: 'bi-check-circle',
      description: 'Testing frameworks and quality assurance',
      skills: [
        {
          name: 'Jest',
          icon: 'devicon-jest-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Testing',
        },
        {
          name: 'Jasmine',
          icon: 'devicon-jasmine-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Testing',
        },

        {
          name: 'Cypress',
          icon: 'devicon-cypressio-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Testing',
        },
        {
          name: 'Karma',
          icon: 'devicon-karma-plain',
          level: 'Intermediate',
          stars: 3,
          category: 'Testing',
        },
        {
          name: 'ESLint',
          icon: 'devicon-eslint-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'Quality',
        },
        {
          name: 'Prettier',
          icon: 'devicon-typescript-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'Quality',
        },
        {
          name: 'commitlint',
          icon: 'devicon-git-plain',
          level: 'Expert',
          stars: 4.5,
          category: 'Quality',
        },
      ],
    },
  ],
};
